// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"context"
	"graphql-service/graph/model"

	"github.com/99designs/gqlgen/graphql"
)

type ResolverRoot interface {
	Mutation() MutationResolver
	Query() QueryResolver
}

type MutationResolver interface {
	CreateTask(ctx context.Context, input model.CreateTaskInput) (*model.Task, error)
	UpdateTask(ctx context.Context, id string, input model.UpdateTaskInput) (*model.Task, error)
	DeleteTask(ctx context.Context, id string) (bool, error)
}

type QueryResolver interface {
	Tasks(ctx context.Context) ([]*model.Task, error)
	Task(ctx context.Context, id string) (*model.Task, error)
}

type executableSchema struct {
	resolvers ResolverRoot
}

func (e *executableSchema) Schema() string {
	return `
type Task {
    id: ID!
    title: String!
    description: String
    dueDate: String
    done: Boolean!
    createdAt: String!
    updatedAt: String!
}

input CreateTaskInput {
    title: String!
    description: String
    dueDate: String
}

input UpdateTaskInput {
    title: String
    description: String
    dueDate: String
    done: Boolean
}

type Query {
    tasks: [Task!]!
    task(id: ID!): Task
}

type Mutation {
    createTask(input: CreateTaskInput!): Task!
    updateTask(id: ID!, input: UpdateTaskInput!): Task!
    deleteTask(id: ID!): Boolean!
}
`
}

func (e *executableSchema) Complexity(typeName, field string, childComplexity int, args map[string]interface{}) (int, bool) {
	return 1, true
}

func NewExecutableSchema(cfg Config) graphql.ExecutableSchema {
	return &executableSchema{}
}

type Config struct {
	Resolvers ResolverRoot
}
